cookie:
  expiry_days: 30
  key: taifa
  name: feeding
credentials:
  usernames:
    bkaitany:
      email: benjaminkipkem@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Benjamin Kaitany
      password: $2y$15$YuwL3VSmTOuCRU1UryJw6uOY328gZ022/yqug3Tvxzg4lVCzba0QO
    jogendo:
      email: jogendo@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Jonam Ogendo
      password: $2b$12$43mqvIzKnppoMBrL5AFOeulS1JQifMwA27HOxlkD23o9tVLa3GSNe
pre-authorized:
  emails:
  - benjaminkipkem@gmail.com
