cookie:
  expiry_days: 30
  key: taifa
  name: feeding
credentials:
  usernames:
    bkaitany:
      email: benjaminkipkem@gmail.com
      failed_login_attempts: 0
      logged_in: true
      name: Benjamin Kaitany
      password: $2a$12$6zXJjWKWfM1d6ejkkZw.WeukeXraHZPNY3dejlUqX9C35D2AMEThu
    jogendo:
      email: jogendo@gmail.com
      failed_login_attempts: 0
      logged_in: false
      name: Jonam Ogendo
      password: $2a$12$6zXJjWKWfM1d6ejkkZw.WeukeXraHZPNY3dejlUqX9C35D2AMEThu
pre-authorized:
  emails:
  - benjaminkipkem@gmail.com
